const GET_STOCK_LIST = 'GET_STOCK_LIST';

const CHANGE_FILTER = 'CHANGE_FILTER';

const GET_PROFILE = 'GET_PROFILE';

const GET_QUOTA = 'GET_QUOTA';

const GET_NEWS = 'GET_NEWS';

export {
  GET_STOCK_LIST, CHANGE_FILTER, GET_PROFILE, GET_QUOTA, GET_NEWS,
};
